enum LibStatus {
    UNDEFINED,
    NO_ERROR,
    ERROR,
    ERR_SPOTIFY_OLD_CODE,
    ERR_SPOTIFY_NEED_REFRESH_TOKEN,
    ERR_SPOTIFY_MISSING_PARAMS,
    ERR_SPOTIFY_NO_AUTH,
    ERR_SPOTIFY_EMPTY_TOKENS,
    ERR_SPOTIFY_REQUEST_FAILED,
    ERR_VK_NO_AUTH,
    ERR_VK_REQUEST_FAILED
}

export { LibStatus }
